// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"

	"github.com/oapi-codegen/nullable"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EditableFormStatus.
const (
	EditableFormStatusActive EditableFormStatus = "active"
	EditableFormStatusPaused EditableFormStatus = "paused"
)

// Valid indicates whether the value is a known member of the EditableFormStatus enum.
func (e EditableFormStatus) Valid() bool {
	switch e {
	case EditableFormStatusActive:
		return true
	case EditableFormStatusPaused:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeEntitlementExpired      ErrorCode = "entitlement_expired"
	ErrorCodeFormLimitReached        ErrorCode = "form_limit_reached"
	ErrorCodeInsufficientScope       ErrorCode = "insufficient_scope"
	ErrorCodeInvalidRequest          ErrorCode = "invalid_request"
	ErrorCodeNotFound                ErrorCode = "not_found"
	ErrorCodeOrganizationSuspended   ErrorCode = "organization_suspended"
	ErrorCodeOrganizationUnavailable ErrorCode = "organization_unavailable"
	ErrorCodePayloadTooLarge         ErrorCode = "payload_too_large"
	ErrorCodeRateLimited             ErrorCode = "rate_limited"
	ErrorCodeUnauthorized            ErrorCode = "unauthorized"
	ErrorCodeUnsupportedMediaType    ErrorCode = "unsupported_media_type"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeEntitlementExpired:
		return true
	case ErrorCodeFormLimitReached:
		return true
	case ErrorCodeInsufficientScope:
		return true
	case ErrorCodeInvalidRequest:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeOrganizationSuspended:
		return true
	case ErrorCodeOrganizationUnavailable:
		return true
	case ErrorCodePayloadTooLarge:
		return true
	case ErrorCodeRateLimited:
		return true
	case ErrorCodeUnauthorized:
		return true
	case ErrorCodeUnsupportedMediaType:
		return true
	default:
		return false
	}
}

// Defines values for FormFieldType.
const (
	Checkbox FormFieldType = "checkbox"
	Email    FormFieldType = "email"
	Select   FormFieldType = "select"
	Text     FormFieldType = "text"
	Textarea FormFieldType = "textarea"
)

// Valid indicates whether the value is a known member of the FormFieldType enum.
func (e FormFieldType) Valid() bool {
	switch e {
	case Checkbox:
		return true
	case Email:
		return true
	case Select:
		return true
	case Text:
		return true
	case Textarea:
		return true
	default:
		return false
	}
}

// Defines values for FormStatus.
const (
	FormStatusActive   FormStatus = "active"
	FormStatusDisabled FormStatus = "disabled"
	FormStatusPaused   FormStatus = "paused"
)

// Valid indicates whether the value is a known member of the FormStatus enum.
func (e FormStatus) Valid() bool {
	switch e {
	case FormStatusActive:
		return true
	case FormStatusDisabled:
		return true
	case FormStatusPaused:
		return true
	default:
		return false
	}
}

// CreateFormRequest defines model for CreateFormRequest.
type CreateFormRequest struct {
	// AllowedOrigins Origins to configure for browser form submissions. Each value
	// must be an absolute HTTP or HTTPS URL. PostMyForm normalizes
	// duplicate and URL-based origin values.
	AllowedOrigins *[]string `json:"allowedOrigins,omitempty"`

	// DestinationEmail The email destination for submission notifications.
	DestinationEmail openapi_types.Email `json:"destinationEmail"`

	// Name The form name.
	Name string `json:"name"`

	// SuccessRedirectUrl An absolute HTTP or HTTPS URL to use after a successful
	// submission. Use null or omit this property to configure no
	// redirect.
	SuccessRedirectUrl nullable.Nullable[string] `json:"successRedirectUrl,omitempty"`
}

// EditableFormStatus A form status that a customer can request.
type EditableFormStatus string

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error Error `json:"error"`
}

// Form defines model for Form.
type Form struct {
	// AllowedOrigins The configured allowed origins for browser submissions.
	AllowedOrigins []string `json:"allowedOrigins"`

	// CreatedAt The time when the form was created.
	CreatedAt time.Time `json:"createdAt"`

	// DestinationEmail The configured email delivery destination.
	DestinationEmail string `json:"destinationEmail"`

	// EndpointId The public submission endpoint ID.
	EndpointId string `json:"endpointId"`

	// Id The stable PostMyForm form ID.
	Id openapi_types.UUID `json:"id"`

	// MinSubmitSeconds The minimum accepted form completion time in seconds.
	MinSubmitSeconds int `json:"minSubmitSeconds"`

	// Name The form name.
	Name string `json:"name"`

	// Slug The account-facing form slug.
	Slug string `json:"slug"`

	// SpamHoneypotField The configured honeypot field name.
	SpamHoneypotField string `json:"spamHoneypotField"`

	// Status The current operational status of the form.
	Status FormStatus `json:"status"`

	// SubmissionUrl The complete public URL that accepts form submissions.
	SubmissionUrl string `json:"submissionUrl"`

	// SuccessRedirectUrl The configured redirect URL, or null when none is set.
	SuccessRedirectUrl nullable.Nullable[string] `json:"successRedirectUrl"`

	// UpdatedAt The time when the form was last updated.
	UpdatedAt time.Time `json:"updatedAt"`
}

// FormField defines model for FormField.
type FormField struct {
	// FieldType The HTML control type used for the form field.
	FieldType FormFieldType `json:"fieldType"`

	// Label The normalized human-readable field label.
	Label string `json:"label"`

	// Name The normalized HTML form field name.
	Name string `json:"name"`

	// Options The normalized select options. This value is null for
	// non-select fields.
	Options nullable.Nullable[[]string] `json:"options"`

	// Required Whether generated HTML marks the field as required.
	Required bool `json:"required"`
}

// FormFieldType The HTML control type used for the form field.
type FormFieldType string

// FormFieldsResponse defines model for FormFieldsResponse.
type FormFieldsResponse struct {
	// Data The complete ordered field configuration.
	Data []FormField `json:"data"`
}

// FormListResponse defines model for FormListResponse.
type FormListResponse struct {
	Data []Form `json:"data"`
}

// FormMutationReceipt defines model for FormMutationReceipt.
type FormMutationReceipt struct {
	// Id The stable PostMyForm form ID.
	Id openapi_types.UUID `json:"id"`

	// Status The current operational status of the form.
	Status FormStatus `json:"status"`

	// UpdatedAt The time when the form was last updated.
	UpdatedAt time.Time `json:"updatedAt"`
}

// FormMutationResponse defines model for FormMutationResponse.
type FormMutationResponse struct {
	Data FormMutationReceipt `json:"data"`
}

// FormResponse defines model for FormResponse.
type FormResponse struct {
	Data Form `json:"data"`
}

// FormSnippet defines model for FormSnippet.
type FormSnippet struct {
	// Html The generated starter HTML form. The snippet posts directly to
	// the form's current PostMyForm submission endpoint.
	Html string `json:"html"`
}

// FormSnippetResponse defines model for FormSnippetResponse.
type FormSnippetResponse struct {
	Data FormSnippet `json:"data"`
}

// FormStatus The current operational status of the form.
type FormStatus string

// PatchFormRequest defines model for PatchFormRequest.
type PatchFormRequest struct {
	// AllowedOrigins Origins to configure for browser form submissions. Each value
	// must be an absolute HTTP or HTTPS URL. Use an empty array to
	// clear all configured origins.
	AllowedOrigins *[]string `json:"allowedOrigins,omitempty"`

	// DestinationEmail The email destination for submission notifications.
	DestinationEmail *openapi_types.Email `json:"destinationEmail,omitempty"`

	// Name The form name.
	Name *string `json:"name,omitempty"`

	// SpamHoneypotField The honeypot field name. The name must not conflict with a
	// reserved field or an existing form field.
	SpamHoneypotField *string `json:"spamHoneypotField,omitempty"`

	// Status A form status that a customer can request.
	Status *EditableFormStatus `json:"status,omitempty"`

	// SuccessRedirectUrl An absolute HTTP or HTTPS URL to use after a successful
	// submission. Use null to clear the configured redirect.
	SuccessRedirectUrl nullable.Nullable[string] `json:"successRedirectUrl,omitempty"`
}

// ReplaceFormField defines model for ReplaceFormField.
type ReplaceFormField struct {
	// FieldType The HTML control type used for the form field.
	FieldType FormFieldType `json:"fieldType"`

	// Label The human-readable field label. PostMyForm trims this value
	// before it validates and stores the field.
	Label string `json:"label"`

	// Name The HTML form field name. PostMyForm trims this value before it
	// validates and stores the field.
	Name string `json:"name"`

	// Options Select option values, or null when the field does not define
	// options.
	//
	// A select field must contain at least one option. A non-select
	// field can use null or an empty array. A non-empty option array is
	// rejected for a non-select field.
	//
	// PostMyForm trims option values and rejects blank, duplicate, and
	// overlong options.
	Options nullable.Nullable[[]string] `json:"options"`

	// Required Whether generated HTML marks the field as required.
	Required bool `json:"required"`
}

// ReplaceFormFieldsRequest defines model for ReplaceFormFieldsRequest.
type ReplaceFormFieldsRequest struct {
	// Fields The complete ordered replacement field collection.
	Fields []ReplaceFormField `json:"fields"`
}

// FormId defines model for FormId.
type FormId = openapi_types.UUID

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// FormLimitReached defines model for FormLimitReached.
type FormLimitReached = ErrorResponse

// FormNotFound defines model for FormNotFound.
type FormNotFound = ErrorResponse

// InvalidRequest defines model for InvalidRequest.
type InvalidRequest = ErrorResponse

// PayloadTooLarge defines model for PayloadTooLarge.
type PayloadTooLarge = ErrorResponse

// RateLimited defines model for RateLimited.
type RateLimited = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = ErrorResponse

// CreateFormJSONRequestBody defines body for CreateForm for application/json ContentType.
type CreateFormJSONRequestBody = CreateFormRequest

// UpdateFormJSONRequestBody defines body for UpdateForm for application/json ContentType.
type UpdateFormJSONRequestBody = PatchFormRequest

// ReplaceFormFieldsJSONRequestBody defines body for ReplaceFormFields for application/json ContentType.
type ReplaceFormFieldsJSONRequestBody = ReplaceFormFieldsRequest
